contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
dirtyInputs: true
id: 77e137b7-d99b-4834-8130-996c1de16464
inputs: []
name: Vision server monitoring
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5a5cb051-b2db-4896-84d3-1861f8cba5eb
      iscommand: false
      name: ""
      version: -1
    taskid: 5a5cb051-b2db-4896-84d3-1861f8cba5eb
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      method:
        simple: GET
      url:
        simple: http://vision.paloaltonetworks.local:3002/keepalive
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a HTTP request with advanced capabilities.
      id: fa5411c6-6765-4192-8606-4315db96f49b
      iscommand: false
      name: Connect to vision server
      script: HttpV2
      type: regular
      version: -1
    taskid: fa5411c6-6765-4192-8606-4315db96f49b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: HttpRequest.Response.Body
          operator: isNotEqualString
          right:
            value:
              simple: alive
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e141e4f0-3f14-42e3-8711-32deeab0d675
      iscommand: false
      name: Keepalive failed?
      type: condition
      version: -1
    taskid: e141e4f0-3f14-42e3-8711-32deeab0d675
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: Check vision, XSOAR instance opp-etac is reporting it is returning
          a non-200 response code
      subject:
        simple: Vision server down notification
      to:
        simple: amurret@paloaltonetworks.com, jjubran@paloaltonetworks.com
      using:
        simple: mailsender
    separatecontext: false
    skipunavailable: false
    task:
      brand: Mail Sender (New)
      description: Send an email.
      id: 1ab5f18a-b882-4706-8166-35cab8a94012
      iscommand: true
      name: Send email
      script: Mail Sender (New)|||send-mail
      type: regular
      version: -1
    taskid: 1ab5f18a-b882-4706-8166-35cab8a94012
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 58961654-47d9-447e-80d0-04e58029df8d
      iscommand: true
      name: Close incident, do not delete, server down
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 58961654-47d9-447e-80d0-04e58029df8d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c55ddec0-33c7-491b-8c03-0f7a896cf1d9
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: c55ddec0-33c7-491b-8c03-0f7a896cf1d9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 138913a5-3852-440e-8e71-fae81a2d3b3c
      iscommand: true
      name: Close and delete, server up
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 138913a5-3852-440e-8e71-fae81a2d3b3c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 465
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${incident.id}
      using:
        simple: core1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: Delete Core incidents.
      id: b9906157-0a88-4fe7-85bb-d36468951549
      iscommand: true
      name: Delete investigation
      script: Core REST API|||core-delete-incidents
      type: regular
      version: -1
    taskid: b9906157-0a88-4fe7-85bb-d36468951549
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 700
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 1180,
        "x": 50,
        "y": 50
      }
    }
  }
